{% set name = "exoplanet-core" %}
{% set version = "0.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/exoplanet_core-{{ version }}.tar.gz
  sha256: c7d52ce595f355387a4ffe545517f1d9a406993f001ec96dd15342cbf1b4b126

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
    - numpy
    - pip
    - pybind11 >=2.6
    - python
    - setuptools_scm
  run:
    - {{ pin_compatible('numpy') }}
    - python

test:
  imports:
    - exoplanet_core

about:
  home: https://docs.exoplanet.codes
  summary: The compiled backend for exoplanet
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://docs.exoplanet.codes
  dev_url: https://github.com/exoplanet-dev/exoplanet-core

extra:
  recipe-maintainers:
    - mwcraig
    - dfm
